- hosts: 
    - c1-node3 
  vars:
      ansible_user: pi
  tasks:
    - name: Verify update required
      become: yes
      shell: if rpi-eeprom-update | grep -q 'update required'; then echo 'true'; else echo 'false'; fi
      register: update
    
    - set_fact: 
        update_required={{ update.stdout }}
    - debug:
        var: update
    - debug:
        var: update_required

    - debug:
        var: update
      when: update_required