# - hosts: c1-master1
#   strategy: debug
#   become: yes
#   user: pi
#   gather_facts: false
#   tasks:

#       - name: manage yaml files
#         yedit:
#           src: ./config.cfg
#           key: users
#           value: test
#     - name: Check if TFTP boot path exists
#       delegate_to: localhost
#       stat: path={{boot_path}}
#       register: bootpath

#     - name: Move/Enable TFTP boot path
#       delegate_to: localhost
#       shell: mv "{{boot_path}}-disable" "{{boot_path}}"
#       when: bootpath.stat.exists == false

#     - name: Enable NFS and TFTP exports
#       become: yes
#       delegate_to: localhost
#       lineinfile:
#         path: "/etc/exports"
#         line: "{{item}}"
#         regex: "{{item}}"
#         state: present
#       register: _exports
#       with_items:
#         - "{{boot_path}} *(rw,sync,no_subtree_check,no_root_squash)"
#         - "{{root_path}} *(rw,sync,no_subtree_check,no_root_squash)"
#     - set_fact: wait_host="{{ ansible_host }}"
#     - name: Waiting 60 secs for server to come back
#       local_action: wait_for host={{wait_host}} port=22 delay=20 connect_timeout=200
#       become: false
#       delegate_to: localhost
#       delegate_facts: true

# - hosts: localhost
#   # strategy: debug
#   gather_facts: no
#   connection: local
#   vars:
#     remote_user: pi
#   roles:
#     - pxe-server

- hosts: c1-master1
  gather_facts: no
  connection: local
  vars:
    remote_user: pi
  roles:
    - pxe-client

- hosts: c1-master1
  # strategy: debug
  gather_facts: no
  connection: local
  vars:
    remote_user: pi
  roles:
    - ssh

- hosts: c1-master1
  become: yes
  user: pi
  roles:
    # - pi-update-rom
    - ubuntu-os

