- hosts: router
  gather_facts: no
  become: yes
  become_method: enable
  user: admin
  connection: network_cli
  vars:
    master_group_name: "k8s_masters"
    worker_group_name: "k8s_workers"
    ansible_network_os: edgeos
    ansible_password: "{{ubnt_password}}"
  roles:
    - role: edgeos
      tags: edgeos, router

- hosts: 
    - k8s_masters
    - k8s_workers
  gather_facts: no
  vars:
    distribution: "Ubuntu"
    distribution_ssh_delay: "{%if  ansible_distribution == ''%}30{%else%}5{%endif%}" 
    distribution_ssh_timeout: "{%if ansible_distribution == '' %}300{%else%}120{%endif%}"
    distribution_ssh_delay_initial: 0
    distribution_ssh_timeout_initial: 10
    distribution_setup_ssh_ping: true
    distribution_setup_ssh_after_sshpass_initial: true
  roles:
    - role: distribution-switch
      tags: ds

- hosts: control_plane
  gather_facts: no
  vars:
    ansible_user: pi
    ansible_password: "{{pi_password}}"
    boot_order: "0xf14"
    force_update: false
    pi_update_rom_has_pxe: false
  roles:
    - role: pi-update-rom
      tags: control-plane, pi-update-rom , os
    - role: ubuntu-os
      tags: control-plane, ubuntu-os, os

- hosts: control_plane
  vars:
    ansible_user: ubuntu
    ansible_password: "{{ubuntu_password}}"
    pi_update_rom_has_pxe: false
  roles:
    - role: common
      tags: control-plane, common, os
    - role: pxe-server
      tags: control-plane, pxe-server, os

- hosts: 
    - k8s_masters
    - k8s_workers
  gather_facts: no
  vars:
    clean: false
    force_update: false
  roles:
    - role: pxe-client
      tags: pxe-client, raspios, os
    - role: pi-update-rom
      tags: pi-update-rom, rapsios, os 
    - role: ubuntu-os
      tags: ubuntu-os, os
    - role: common
      tags: common, os
    - role: docker
      tags: docker
    # - role: k8s
    #   tags: k8s

