- hosts: router
  gather_facts: no
  become: yes
  become_method: enable
  user: admin
  connection: network_cli
  vars:
    master_group_name: "k8s_masters"
    worker_group_name: "k8s_workers"
    ansible_network_os: edgeos
    ansible_password: "{{ubnt_password}}"
  roles:
    - edgeos

- hosts: control_plane
  gather_facts: no
  vars:
    ansible_user: pi
    ansible_password: "{{pi_password}}"
    disable_pxe: false
    boot_order: "0xf14"
    force_update: false
  roles:
    - pi-update-rom
    - ubuntu-os

- hosts: control_plane
  vars:
    ansible_user: ubuntu
    ansible_password: "{{ubuntu_password}}"
    disable_pxe: false
  roles:
    - common
    - pxe-server

- hosts: 
    - k8s_masters
    - k8s_workers
  gather_facts: no
  user: pi
  vars:
    ssh_user: pi
    ssh_pass: "{{pi_password}}"
    clean: false
    force_update: false
  roles:
    - pxe-client
    - pi-update-rom
    - ubuntu-os
    - common

