- hosts: router
  gather_facts: no
  become: yes
  become_method: enable
  user: admin
  connection: network_cli
  vars:
    master_group_name: "k8s_masters"
    worker_group_name: "k8s_workers"
    ansible_network_os: edgeos
    ansible_password: "{{ubnt_password}}"
  roles:
    - role: edgeos
      tags: edgeos, router

- hosts: 
    - k8s_masters
    - k8s_workers
  gather_facts: no
  vars:
    force_pxe_boot_state: "disabled"
    force_usb_boot_state: "disabled"
  roles:
    - role: distribution-switch
      tags: ds, distribution-switch, os

# - hosts: control_plane
#   gather_facts: no
#   vars:
#     force_update: false
#   roles:
#     - role: pi-update-rom
#       tags: control-plane, pi-update-rom , os
#     # - role: ubuntu-os
#     #   tags: control-plane, ubuntu-os, os

- hosts: control_plane
  gather_facts: no
  roles:
    # - role: common
    #   tags: control-plane, common, os
    - role: pikvm-os
      tags: control-plane, pikvm-os, os
    - role: pxe-server
      tags: control-plane, pxe-server, os

- hosts: 
    - k8s_masters
    - k8s_workers
  gather_facts: no
  vars:
    clean: false
    force_update: false
  roles:
    - role: pxe-client
      tags: pxe-client,pc, raspios, os
    - role: pi-update-rom
      tags: pi-update-rom,pur, rapsios, os 
    - role: manjaro-os
      tags: manjaro-os
    - role: raspbian-os
      tags: raspbian-os
    - role: ubuntu-os
      tags: ubuntu-os
    - role: common
      tags: common, os
    - role: docker
      tags: docker
    - role: k8s
      tags: k8s, k8s-os
    - role: k8s-reset
      tags: k8s-reset
    - role: k8s-join
      tags: k8s-join, k8s-os
    - role: metallb
      tags: metallb, k8s-join
