# - hosts: 
#     - k8s_workers
#     - k8s_masters
#   gather_facts: false
#   tasks:
#     - ping:

- hosts: 
    - k8s_masters
  gather_facts: false
  user: pi
  tasks:
    - ping:
      ignore_errors: true