- include: ssh.yml

- hosts: all
  user: ubuntu
  become: yes
  become_user: root
  become_method: sudo
  tasks:
    - reboot:
        msg: "Reboot by Ansible"
        reboot_timeout: 120   # (= 5 minutes)