- hosts: all
  user: pi
  become: yes
  become_user: root
  become_method: sudo
  gather_facts: false
  tasks:
   - name: Include task list in play
     include: reboot-task.yml
- include: ping.yml