# - hosts: 
#     - k8s_workers
#     - k8s_masters
#   gather_facts: false
#   user: ubuntu
#   tasks:
#     - name: Include task list in play
#       include: reboot-task.yml

- hosts: 
    - k8s_masters
  gather_facts: false
  user: pi
  tasks:
    - name: Include task list in play
      include: reboot-task.yml