- hosts: all
  # strategy: debug
  gather_facts: no
  connection: local
  vars:
    remote_user: pi
  roles:
    - ssh

- hosts: all
  become: yes
  user: pi
  roles:
    # - pi-update-rom
    - ubuntu-os

- hosts: all
  # strategy: debug
  # gather_facts: yes
  user: ubuntu
  become: yes
  become_user: root
  become_method: sudo
  roles:
    - common
    # - rpi_exporter
    # - node_exporter

- hosts: k8s_masters
  user: ubuntu
  become: yes
  become_user: root
  become_method: sudo
  roles:
    # - monitoring_server
    - docker
    - k8s
    - k8s-master
    - helm
    # - cluster_monitoring

- hosts: k8s_worker
  user: ubuntu
  become: yes
  become_user: root
  become_method: sudo
  roles:
    - docker
    - k8s
    - k8s-node
