      persistentVolumeClaim:
        enabled: true
        accessModes:
          - ReadWriteMany
        storageClass: rook-ceph-block
      # extraEnvVars:
      #   ServerIP: 192.168.0.245
      # webHttp: "55080"
      # webHttps: "55443"
      # ingress:
      #   enabled: true
      serviceTCP:
        annotations:
          metallb.universe.tf/allow-shared-ip: pihole-svc
        loadBalancerIP: '{{ load_balancer_server_ip_tcp }}'
        type: LoadBalancer
      serviceUDP:
        annotations:
          metallb.universe.tf/allow-shared-ip: pihole-svc
        loadBalancerIP: '{{ load_balancer_server_ip_udp }}'
        type: LoadBalancer
      # resources:
      #   limits:
      #     cpu: 200m
      #     memory: 256Mi
      #   requests:
      #     cpu: 100m
      #     memory: 128Mi
      # If using in the real world, set up admin.existingSecret instead.
      adminPassword: admin
      replicaCount: 3
