- name: Set DHCP static ip, MAC and hostname
  edgeos_config:
    lines: 
      - set service dhcp-server shared-network-name {{subnet_name}} subnet {{subnet}} static-mapping {{item}} ip-address {{hostvars[item].ansible_host}}
      - set service dhcp-server shared-network-name {{subnet_name}} subnet {{subnet}} static-mapping {{item}} mac-address {{hostvars[item].node_mac}}
  with_items: "{{ groups[master_group_name] +  groups[worker_group_name]   +  groups['control_plane'] }}"
  when: hostvars[item].ansible_host is defined


- name: Set TFTP Server Name
  run_once: true
  edgeos_config:
    lines: 
      - set service dhcp-server shared-network-name {{subnet_name}} subnet {{subnet}} tftp-server-name {{hostvars[item].ansible_host}}
  with_items: "{{  groups['control_plane'] }}"