
- name: Check if kube confing exists for {{remote_user}}
  stat: path=/home/{{remote_user}}/.kube
  register: kube

- name: Initialize the Kubernetes cluster using kubeadm
  run_once: 'yes'
  command: "kubeadm init --apiserver-advertise-address='{{ node_ip }}' --apiserver-cert-extra-sans='{{ node_ip }}' --node-name {{ ansible_host }} --pod-network-cidr=192.168.0.0/16"
  when: not kube.stat.exists

- name: Setup kubeconfig for {{remote_user}}
  command: "{{ item }}"
  with_items:
    - mkdir -p /home/{{remote_user}}/.kube
    - cp -i /etc/kubernetes/admin.conf /home/{{remote_user}}/.kube/config
    - chown {{remote_user}}:{{remote_user}} /home/{{remote_user}}/.kube/config
  when: not kube.stat.exists

- name: Install calico pod network
  become: false
  command: kubectl apply -f https://docs.projectcalico.org/manifests/calico.yaml

- name: Generate join command
  command: kubeadm token create --print-join-command
  register: join_command

- name: Copy join command to local file
  local_action: copy content="kubeadm reset --force \n {{ join_command.stdout_lines[0] }}" dest="~/join-command"
  ignore_errors: 'yes'
  become: false