
- name: Check if kube confing exists for {{remote_user}}
  stat: path=/home/{{remote_user}}/.kube
  register: kube

- name: Initialize the Kubernetes cluster using kubeadm
  run_once: 'yes'
  command: "kubeadm init --apiserver-advertise-address='{{ node_ip }}' --apiserver-cert-extra-sans='{{ node_ip }}' --node-name {{ ansible_host }} --pod-network-cidr=192.168.0.0/16"
  when: not kube.stat.exists

- name: Create directory kubeconfig for {{remote_user}}
  command: "{{ item }}"
  become: false
  with_items:
    - mkdir -p /home/{{remote_user}}/.kube
  when: not kube.stat.exists

- name: Setup kubeconfig for {{remote_user}}
  command: "{{ item }}"
  become: yes
  with_items:
    - cp -i /etc/kubernetes/admin.conf /home/{{remote_user}}/.kube/config
    - chown {{remote_user}}:{{remote_user}} /home/{{remote_user}}/.kube/config
  when: not kube.stat.exists

- name: Install calico pod network
  become: false
  command: kubectl apply -f https://docs.projectcalico.org/manifests/calico.yaml

- name: Kubectl bash completion
  become: yes
  become_user: root
  shell: kubectl completion bash > /etc/bash_completion.d/kubectl

- name: Kubectl alias complete
  become: false
  lineinfile:
      path: ~/.bashrc
      line: "{{item}}"
      regex: "{{item}}"
      state: present
  with_items:
  - alias k=kubectl
  - complete -F __start_kubectl k