clean: false
boot_order: "0xf124"
force_mount_osdisk: true
set_boot_path: false
distribution_setup_ssh_after_sshpass_initial: true
distribution_setup_ssh_ping: true
distribution_setup_ssh_after_sshpass: true
distribution_ssh_delay_initial:  0
distribution_ssh_timeout_initial: 10
distribution_ssh_delay:  20
distribution_ssh_timeout: 300
force_disable_pxe: false
force_enable_pxe: false
force_disable_ubuntu: false
force_enable_ubuntu: false
skip_ubuntu_clean: false
has_pxe: true
