- set_fact:
    mount_boot_path: "/media/{{inventory_hostname}}-sda1"
    mount_root_path: "/media/{{inventory_hostname}}-sda2"
    ansible_user: pi
    pxe_server: "{{groups['control_plane'][0]}}"
    pxe_user: "root"

- name: Include ssh initial
  vars:
    ssh_delay: "0" 
    ssh_timeout: "20"
    ssh_ping: true
    clean: true
  include_role:
    name: ssh
  when: ansible_distribution is not defined 
    or ansible_distribution is defined 
    and ansible_distribution == '' 

- name: Creates su directory
  become: yes
  file:
    path: "{{item}}"
    state: directory
  with_items:
    - "{{mount_boot_path}}"
    - "{{mount_root_path}}"
  when: >  
    "/media" in mount_boot_path
    and "/media" in mount_root_path 

- name: Creates directory
  file:
    path: "{{item}}"
    state: directory
    force: true
  with_items:
    - "{{ubuntu_img_dir}}"

- name: Gather facts from {{pxe_server}}
  ansible.builtin.setup:
  delegate_to: "{{pxe_server}}"
  connection: ssh
  vars:
    ansible_user: "root"

- name: Print ip from available facts
  ansible.builtin.debug:
    var: ansible_facts['all_ipv4_addresses'][0]

- name: Mount up ubuntu download
  become: yes
  shell: mount -t nfs "{{ansible_facts['all_ipv4_addresses'][0]}}:/srv/nfs/images" "{{ubuntu_img_dir}}"
  register: mount
  failed_when: >
    mount.rc != 0 
    and 'already mounted on' not in mount.stderr
    or 'not mounted.' in mount.stderr
  changed_when: >
    mount.rc == 0 

- name: Check if archive img exists
  delegate_to: "{{pxe_server}}"
  connection: ssh
  vars:
    ansible_user: "root"
  run_once: true
  stat: path="/srv/nfs/images/ubuntu-22.04.1-preinstalled-server-arm64+raspi.img"
  register: img

- name: Download ubuntu image
  delegate_to: "{{pxe_server}}"
  connection: ssh
  vars:
    ansible_user: "root"
  run_once: true
  get_url:
    url: https://cdimage.ubuntu.com/releases/22.04/release/ubuntu-22.04.1-preinstalled-server-arm64+raspi.img.xz
    dest: "/srv/nfs/images"
  when: img.skipped is not defined and img.stat.exists == false

- name: Extract
  delegate_to: "{{pxe_server}}"
  connection: ssh
  vars:
    ansible_user: "root"
  run_once: true
  become: yes
  shell: xz -d /srv/nfs/images/*.img.xz
  when: img.skipped is not defined and img.stat.exists == false

- name: Write to disk
  become: yes
  shell: dd bs=64k if={{ubuntu_img_dir}}/ubuntu-22.04.1-preinstalled-server-arm64+raspi.img of={{os_disk}} iflag=fullblock oflag=direct

- name: Check if os_disk exists
  stat: 
    path: "{{os_disk}}"
  register: os_disk_result
- debug:
    var: os_disk_result.changed, bootconfig_order.changed, bootconf_extract.changed
    
- name: Mount up ubuntu disk boot partition
  become: yes
  shell: mount "{{os_disk}}1" "{{mount_boot_path}}"
  register: mount
  when: >
    "/media" in mount_boot_path 
  failed_when: >
    mount.rc != 0 
    and 'already mounted on' not in mount.stderr
    or 'not mounted.' in mount.stderr
  changed_when: >
    mount.rc == 0  
    
- name: Mount up ubuntu disk root partition
  become: yes
  shell: mount "{{os_disk}}2" "{{mount_root_path}}"
  register: mount2
  when: >
    "/media" in mount_root_path 
  failed_when: >
    mount2.rc != 0 
    and 'already mounted on' not in mount2.stderr
    or 'not mounted.' in mount2.stderr
  changed_when: >
    mount2.rc == 0  

# - name: Netplan 99
#   become: yes
#   lineinfile:
#     path: "{{mount_root_path}}/etc/cloud/cloud.cfg.d/99-disable-network-config.cfg"
#     line: "{{item}}"
#     regex: "{{item}}"
#     state: present
#     create: yes
#   with_items:
#     - "network: {config: disabled}"

# - name: Netplan 50
#   become: yes
#   lineinfile:
#     path: "{{mount_root_path}}/etc/netplan/50-cloud-init.yaml"
#     line: "              driver: bcmgenet"
#     regex: "              driver: bcmgenet smsc95xx lan78xx"
#     state: present
 
 
- name: Expire user password
  become: yes
  lineinfile:
    path: "{{mount_boot_path}}/user-data"
    line: "  expire: false"
    regex: "  expire: true"
    state: present

- name: Set user-data hostname
  become: yes
  lineinfile:
    path: "{{mount_boot_path}}/user-data"
    line: "hostname: {{inventory_hostname}}"
    regex: "hostname"
    state: present

# - name: Disable Bluetooth and WiFi
#   become: yes
#   lineinfile:
#     path: "{{mount_boot_path}}/config.txt"
#     line: "{{item}}"
#     regex: "{{item}}"
#     state: present
#   register: _config
#   with_items:
#   - dtoverlay=disable-wifi
#   - dtoverlay=disable-bt

- name: Include distribution switch to Ubuntu
  vars:
    distribution: "Ubuntu"
    clean: true
    distribution_ssh_delay_initial: 1 
    distribution_ssh_timeout_initial: 1
    distribution_setup_ssh_after_sshpass_initial: true
    distribution_ssh_user_after_reboot: ubuntu
    distribution_ssh_delay: 30 
    distribution_ssh_timeout: 90
    distribution_setup_ssh_ping: true
    force_pxe_boot_state: true
  include_role:
    name: distribution-switch