- name: Check if archive img exists
  stat: path=./ubuntu-20.10-preinstalled-server-arm64+raspi.img.xz
  register: img

- name: Download ubuntu image
  get_url:
    url: https://cdimage.ubuntu.com/releases/20.10/release/ubuntu-20.10-preinstalled-server-arm64+raspi.img.xz
    dest: ./
  when: img.stat.exists == false

- name: Format disk
  shell: "dd if=/dev/zero of={{os_disk}} bs=1M count=2"

- name: Extract and write to disk
  shell: xzcat ./ubuntu-20.10-preinstalled-server-arm64+raspi.img.xz | dd bs=4M of={{os_disk}} conv=fsync status=progress

- name: Mount up root
  mount:
    src: "{{os_disk}}2"
    path: "./rootmnt"
    state: mounted
    fstype: ext4

- name: Configure Cloud Init
  template:
    src: "etc/cloud/cloud.yml.j2"
    dest: "./rootmnt/etc/cloud/cloud.cfg"

- name: Restart server
  shell: sleep 2 && /sbin/shutdown -r now "Ansible system"
  async: 1
  poll: 0

- name: Check if TFTP boot path exists
  delegate_to: localhost
  stat: path={{boot_path}}
  register: bootpath

- name: Move/Disable TFTP boot path
  delegate_to: localhost
  shell: mv "{{boot_path}}" "{{boot_path}}-disable"
  when: bootpath.stat.exists

- name: Disable NFS and TFTP exports
  become: yes
  delegate_to: localhost
  lineinfile:
    path: "/etc/exports"
    line: "{{item}}"
    state: absent
  register: _exports
  with_items:
    - "{{boot_path}} *(rw,sync,no_subtree_check,no_root_squash)"
    - "{{root_path}} *(rw,sync,no_subtree_check,no_root_squash)"

- name: Restart services
  delegate_to: localhost
  systemd:
    name: "{{item}}"
    state: "restarted"
  with_items:
    - nfs-server
    - tftpd-hpa
  when: _exports.changed

- set_fact: wait_host="{{ ansible_host }}"
- name: Waiting 60 secs for server to come back
  local_action: wait_for host={{wait_host}} port=22 delay=20 connect_timeout=200
  become: false
  delegate_to:  127.0.0.1

- name: Cleanup ssh hosts
  delegate_to: localhost
  run_once: true
  shell: echo "" > ~/.ssh/known_hosts
  
- name: Distribute the ssh key to the remote hosts
  delegate_to: localhost
  connection: local
  become: yes
  shell: "ssh-copy-id -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa.pub ubuntu@{{ ansible_host }} -f"
  register: ssh_copy_id_execution

