
- name: Waiting for server to come back
  local_action: wait_for host={{ ansible_host }} port=22 delay=2 connect_timeout=200
  become: false
  delegate_to: localhost
  delegate_facts: true

- name: Check if archive img exists
  stat: path=./ubuntu-20.10-preinstalled-server-arm64+raspi.img.xz
  register: img

- name: Download ubuntu image
  get_url:
    url: https://cdimage.ubuntu.com/releases/20.10/release/ubuntu-20.10-preinstalled-server-arm64+raspi.img.xz
    dest: ./
  when: img.stat.exists == false

- name: UMount up root
  become: yes
  ignore_errors: true
  shell: umount "{{item}}"
  with_items:
    - "{{os_disk}}1"
    - "{{os_disk}}2" 
  failed_when: umount.stderr_lines is defined and umount.stderr_lines[0].find("not mounted.")

- name: Wipefs
  become: yes
  shell: "wipefs -a {{os_disk}}"
  when: clean

- name: Extract and write to disk
  become: yes
  shell: xzcat ./ubuntu-20.10-preinstalled-server-arm64+raspi.img.xz | dd bs=64k of={{os_disk}} iflag=fullblock oflag=direct

- name: Creates directory
  become: yes
  file:
    path: "{{item}}"
    state: directory
  with_items:
    - "./rootmnt"
    - "./bootmnt"

- name: Mount up root
  become: yes
  shell: mount "{{os_disk}}2" "./rootmnt"
 
- name: Mount up boot
  become: yes
  shell: mount "{{os_disk}}1" "./bootmnt"

- name: Expire user password
  become: yes
  lineinfile:
    path: ./bootmnt/user-data
    line: "  expire: false"
    regex: "  expire: true"
    state: present

- name: Disable Bluetooth and WiFi
  become: yes
  lineinfile:
    path: "./bootmnt/config.txt"
    line: "{{item}}"
    regex: "{{item}}"
    state: present
  register: _config
  with_items:
  - dtoverlay=disable-wifi
  - dtoverlay=disable-bt

- name: Restart server
  ignore_errors: true
  ignore_unreachable: true
  connection: ssh 
  shell: sleep 0 && /sbin/shutdown -r now "Ansible system"
  async: 1
  poll: 0
  become: yes
  vars:
    ansible_user: pi
    ansible_password: "{{pi_password}}"
  register: restart

- name: Include ssh
  include_role:
    name: ssh
  vars:
    ssh_delay: 60
    ssh_timeout: 180
    ssh_user: ubuntu
    ansible_user: ubuntu
    ssh_pass: "{{ubuntu_password}}" 
    ansible_password: "{{ubuntu_password}}"