- name: Generate join command
  delegate_to: "{{ groups['k8s_masters'][0] }}"
  vars:
    ansible_user: pi
  connection: ssh
  become: false
  command: kubeadm token create --print-join-command
  register: join_command

- name: Join the node to cluster
  become: yes
  command: "{{join_command.stdout}}"
  register: join_result
  changed_when: '"This node has joined the cluster:" in join_result.stdout_lines'
  failed_when: '"This node has joined the cluster:" not in join_result.stdout_lines and "already exists in the cluster" not in join_result.stderr'
  
- debug:
    var: join_result