- name: Include ssh
  include_role:
    name: ssh

- name: Check if ubuntu is enabled
  vars:
    ansible_user: ubuntu
  become: yes
  stat: path=/boot/firmware/start4.elf
  register: bootpath
  when: ansible_distribution is defined and ansible_distribution == 'Ubuntu'
    
- debug:
    var: bootpath
- name: Disable usb boot to switch to raspberry
  vars:
    ansible_user: ubuntu
  become: yes
  shell: mv "/boot/firmware/{{item}}" "/boot/firmware/{{item}}.disable"
  when: bootpath.skipped is not defined and bootpath.stat.exists
  with_items:
    - "start4.elf"
    - "start.elf"

- name: Restart ubuntu server 
  shell: sleep 2 && /sbin/shutdown -r now "Ansible system"
  async: 1
  poll: 0
  become: yes
  register: restart
  vars:
    ansible_user: ubuntu
  when: ansible_distribution is defined and ansible_distribution == 'Ubuntu'

- name: Include ssh
  include_role:
    name: ssh

- name: Fix slow apt update
  vars:
    ansible_user: pi
  become: yes
  sysctl:
    name: "{{item}}"
    value: 1
    sysctl_set: yes
    state: present
    reload: yes
  with_items:
    - net.ipv6.conf.all.disable_ipv6
    - net.ipv6.conf.default.disable_ipv6
    - net.ipv6.conf.lo.disable_ipv6
  register: ip6

- name: Restart service networking
  vars:
    ansible_user: pi
  become: yes
  service:
    name: networking
    state: restarted
  when: ip6.changed

- name: Verify update required
  vars:
    ansible_user: pi
  become: yes
  shell: if rpi-eeprom-update | grep -q 'update required'; then echo 'true'; else echo 'false'; fi
  register: update
- set_fact: update_required={{ update.stdout }}

- name: 'Update and upgrade apt packages'
  vars:
    ansible_user: pi
  become: yes
  apt:
    upgrade: 'yes'
    update_cache: yes
    cache_valid_time: 86400
  register: apt_update
  when: update_required or force_update

- name: Verify update available
  vars:
    ansible_user: pi
  become: yes
  shell: if rpi-eeprom-update | grep -q 'update available'; then echo 'true'; else echo 'false'; fi
  register: update
  
- set_fact: update_required={{ update.stdout }}

- name: Setup rpi-eeprom-update branch
  vars:
    ansible_user: pi
  become: yes
  lineinfile:
    path: /etc/default/rpi-eeprom-update
    line: 'FIRMWARE_RELEASE_STATUS="latest"'
    regex: "FIRMWARE_RELEASE_STATUS="
    state: present

- name: Extract bootconf
  vars:
    ansible_user: pi
  become: yes
  shell: rpi-eeprom-config > ./bootconf.txt

- name: Setup boot configuration
  vars:
    ansible_user: pi
  lineinfile:
    path: "./bootconf.txt"
    line: "{{item}}"
    regex: "{{item}}"
    state: present
  register: bootconf
  with_items:
   - "BOOT_ORDER={{boot_order}}"
   - "MAX_RESTARTS=1"
   - "SD_BOOT_MAX_RETRIES=1"
   - "NET_BOOT_MAX_RETRIES=1"
  
- name: Update ROM
  vars:
    ansible_user: pi
  become: yes
  shell: "{{item}}"
  with_items:
   - "rpi-eeprom-config --apply ./bootconf.txt"
  when: >
    update_required 
    or force_update 
    or bootconf.changed

- name: Include task list in play
  vars:
    ansible_user: pi
  include: reboot-task.yml
  when: > 
    update_required 
    or force_update 
    or bootconf.changed

