- name: Check if pxe is disabled
  delegate_to: localhost
  stat: path={{boot_path}}-disable
  register: bootpath

- name: Enable pxe boot
  become: yes
  delegate_to: localhost
  shell: mv "{{boot_path}}-disable" "{{boot_path}}"
  when: bootpath.stat.exists == true

- set_fact: wait_host="{{ ansible_host }}"
  when: bootpath.stat.exists == true
- name: Waiting 60 secs for server to come back
  local_action: wait_for host={{wait_host}} port=22 delay=20 connect_timeout=200
  become: false
  delegate_to: localhost
  delegate_facts: true
  when: bootpath.stat.exists == true

- name: Fix slow apt update
  become: yes
  sysctl:
    name: "{{item}}"
    value: 1
    sysctl_set: yes
    state: present
    reload: yes
  with_items:
    - net.ipv6.conf.all.disable_ipv6
    - net.ipv6.conf.default.disable_ipv6
    - net.ipv6.conf.lo.disable_ipv6
  register: ip6

- name: Restart service networking
  become: yes
  service:
    name: networking
    state: restarted
  when: ip6.changed

- name: Hold apt packages
  become: yes
  dpkg_selections:
    name: "{{item}}"
    selection: hold
  with_items:
    - libraspberrypi-bin 
    - libraspberrypi-dev 
    - libraspberrypi-doc 
    - libraspberrypi0
    # - raspberrypi-bootloader 
    - raspberrypi-kernel 
    - raspberrypi-kernel-headers

- name: 'Update and upgrade apt packages'
  become: yes
  apt:
    upgrade: 'yes'
    update_cache: yes
    cache_valid_time: 86400

- name: Setup rpi-eeprom-update branch
  become: yes
  lineinfile:
    path: /etc/default/rpi-eeprom-update
    line: 'FIRMWARE_RELEASE_STATUS="stable"'
    regex: "FIRMWARE_RELEASE_STATUS="
    state: present

- name: Check if ROM exists
  stat: path=/lib/firmware/raspberrypi/bootloader/stable/{{pi_eeprom_version}}.bin
  register: rom

- name: Extract bootconf
  shell: rpi-eeprom-config /lib/firmware/raspberrypi/bootloader/stable/{{pi_eeprom_version}}.bin > ./bootconf.txt

- name: Setup boot configuration
  lineinfile:
    path: "./bootconf.txt"
    line: "{{item}}"
    regex: "{{item}}"
    state: present
  register: bootconf
  with_items:
   - "BOOT_ORDER=0xf421"
   - "MAX_RESTARTS=1"
   - "SD_BOOT_MAX_RETRIES=1"
   - "NET_BOOT_MAX_RETRIES=1"

- name: Update ROM
  become: yes
  shell: "{{item}}"
  with_items:
   - "rpi-eeprom-config --out ./{{pi_eeprom_version}}-netboot.bin --config ./bootconf.txt /lib/firmware/raspberrypi/bootloader/stable/{{pi_eeprom_version}}.bin"
   - "rpi-eeprom-update -d -f ./{{pi_eeprom_version}}-netboot.bin"

- name: Include task list in play
  include: reboot-task.yml