- name: Create nginx-deployment
  become: false
  k8s:
    state: present
    definition:
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        namespace: default
        name: nginx-deployment
      spec:
        selector:
          matchLabels:
            app: nginx
        replicas: 3
        template:
          metadata:
            labels:
              app: nginx
          spec:
            containers:
            - name: nginx
              image: nginx:latest
              ports:
              - containerPort: 80

- name: Create nginx-service
  become: false
  k8s:
    state: present
    definition:
      apiVersion: v1
      kind: Service
      metadata:
        namespace: default
        name: nginx
      spec:
        type: LoadBalancer
        selector:
          app: nginx
        ports:
        - port: 80
          name: http