
- name: Mount up root
  mount:
    src: "{{os_disk}}2"
    path: "./rootmnt"
    state: mounted
    fstype: ext4

- name: Configure Cloud Init
  template:
    src: "etc/cloud/cloud.yml.j2"
    dest: "./rootmnt/etc/cloud/cloud.cfg"
