
    # - name: Print some debug information 
    #   vars: 
    #     msg: |
    #       # Module Variables ("vars"):
    #       # --------------------------------
    #       # {{ vars | to_nice_json }} 
          
    #       # Environment Variables ("environment"):
    #       # --------------------------------
    #       # {{ environment | to_nice_json }} 
          
    #       # GROUP NAMES Variables ("group_names"):
    #       # --------------------------------
    #       # {{ group_names | to_nice_json }}
          
    #       # GROUPS Variables ("groups"):
    #       # --------------------------------
    #       # {{ groups | to_nice_json }}
          
    #       HOST Variables ("hostvars"):
    #       --------------------------------
    #       {{ hostvars | to_nice_json }} 
    
    #   debug: 
    #     msg: "{{ msg.split('\n') }}"       
    #   tags: debug_info

- name: Get dns service address
  become: false
  command: kubectl get services --all-namespaces -ojsonpath='{.items[?(@.metadata.name=="kube-dns")].spec.clusterIP}'
  register: kubednsaddress

- name: Wait for dns to be ready
  wait_for: 
    host: "{{ kubednsaddress.stdout }}" 
    port: 53 
    state: started 
    timeout: 1800
