- name: Include ssh initial
  vars:
    ssh_delay: "0"
    ssh_timeout: "20"
    ssh_ping: true
    clean: true
  include_role:
    name: ssh
  when: ansible_distribution is not defined
    or ansible_distribution is defined
    and ansible_distribution == ''

- name: Install packages
  become: yes
  ansible.builtin.package:
    name: "{{ item }}"
    state: present
  with_items:
    - apt-transport-https
    - ca-certificates
    - curl
    - git
    - bash-completion
    - btrfs-progs
    - kpartx
    - e2fsck
    - hdparm
    - smartmontools


