- name: Include ssh initial
  vars:
    ssh_delay: "0"
    ssh_timeout: "20"
    ssh_ping: true
    clean: true
  include_role:
    name: ssh
  when: ansible_distribution is not defined
    or ansible_distribution is defined
    and ansible_distribution == ''

- name: Install packages
  become: yes
  ansible.builtin.package:
    name: "{{ item }}"
    state: present
  with_items:
    - apt-transport-https
    - ca-certificates
    - curl
    # - gnupg-agent
    # - software-properties-common
    # - python3-pip
    # - python3-setuptools
    # - aptitude
    # - golang
    - git
    - bash-completion
    # - nfs-common
    # - dphys-swapfile
    - lvm2
    - xfsprogs
    - btrfs-progs
    - rsync
    - lsb-release
    - arch-install-scripts
    - kpartx
    - nmap
    - iperf3
