

- name: Generate cert key
  delegate_to: "{{ groups['k8s_masters'][0] }}"
  vars:
    ansible_user: root
  connection: ssh
  become: false
  command: kubeadm init phase upload-certs --upload-certs
  register: key_command
  
- name: Generate join command
  delegate_to: "{{ groups['k8s_masters'][0] }}"
  vars:
    ansible_user: root
  connection: ssh
  become: false
  command: kubeadm token create --print-join-command
  register: join_command

- name: Create join command
  set_fact: 
    signed_join_command: "{{join_command.stdout}} --control-plane --certificate-key='{{key_command.stdout_lines[2]}}' --apiserver-advertise-address='{{ ansible_host }}' --node-name {{ inventory_hostname }}"
 
- debug:  
    var: signed_join_command

- name: Join the master node to cluster
  become: yes
  command: "{{ signed_join_command }}"
  register: join_result
  changed_when: '"This node has joined the cluster and a new control plane instance was created:" in join_result.stdout_lines'
  failed_when: '"This node has joined the cluster and a new control plane instance was created:" not in join_result.stdout_lines and "\t[ERROR Port-10250]: Port 10250 is in use" not in join_result.stderr'
