- name: Renew DHCP
  become: yes
  shell: "dhclient -r; dhclient"
  when: "ansible_host not in ansible_all_ipv4_addresses"

- name: Update and upgrade apt packages
  become: yes
  apt:
    upgrade: yes
    update_cache: yes
    cache_valid_time: 86400

- name: Install packages
  become: yes
  apt:
    name: "{{ packages }}"
    state: present
    update_cache: yes
  vars:
    packages:
    - nfs-kernel-server
    - kpartx 
    - unzip 
    - tftpd-hpa

- name: Check if version img exists
  find: 
    paths: ./
    patterns: "*raspbian-buster-lite.img"
  register: findimg

- name: Rename file
  shell: mv ./*raspbian-buster-lite.img ./raspbianos.img
  when: findimg.matched > 0

- name: Check if raspbian os img exists
  find: 
    paths: ./
    patterns: raspbianos.img
  register: osimg

- name: Unarchive a file that needs to be downloaded
  unarchive:
    src:  https://downloads.raspberrypi.org/raspios_lite_armhf_latest
    dest: ./
    remote_src: yes
  when: osimg.matched == 0

