- name: Renew DHCP
  become: yes
  shell: "dhclient -r; dhclient"
  when: "ansible_host not in ansible_all_ipv4_addresses"

- name: Update and upgrade apt packages
  become: yes
  apt:
    upgrade: yes
    update_cache: yes
    cache_valid_time: 86400

- name: Install packages
  become: yes
  apt:
    name: "{{ packages }}"
    state: present
    update_cache: yes
  vars:
    packages:
    - nfs-kernel-server
    - kpartx 
    - unzip 
    - tftpd-hpa

- name: Creates directory
  become: yes
  file:
    path: "{{item}}"
    state: directory
    owner: nobody
    group: nogroup
    mode: 0777
  with_items:
    - "/srv/nfs"
    - "/srv/tftp"
    

