- name: Update and upgrade apt packages
  apt:
    upgrade: yes
    update_cache: yes
    cache_valid_time: 86400

- name: Install packages
  apt:
    name: "{{ packages }}"
    state: present
    update_cache: yes
  vars:
    packages:
    - nfs-kernel-server
    - kpartx 
    - unzip 
    - tftpd-hpa

- name: Check if version img exists
  find: 
    paths: ./
    patterns: "*raspbian-buster-lite.img"
  register: findimg

- name: Rename file
  shell: mv ./*raspbian-buster-lite.img ./raspbianos.img
  when: findimg.matched > 0

- name: Check if raspbian os img exists
  find: 
    paths: ./
    patterns: raspbianos.img
  register: osimg

- name: Unarchive a file that needs to be downloaded
  unarchive:
    src:  https://downloads.raspberrypi.org/raspbian_lite_latest
    dest: ./
    remote_src: yes
  when: osimg.matched == 0

- name: Mount img
  shell: "x=$(kpartx -a -v ./*.img | awk '{print $3}'); echo $x  | cut -d' ' -f1 |rev| cut -c3- | rev"
  register: partx_result

- debug:
   var: partx_result

- name: Mount up boot
  mount:
    src: "/dev/mapper/{{partx_result.stdout}}p1"
    path: "./bootmnt"
    state: mounted
    fstype: vfat

- name: Mount up root
  mount:
    src: "/dev/mapper/{{partx_result.stdout}}p2"
    path: "./rootmnt"
    state: mounted
    fstype: ext4
