- name: Include ssh initial
  vars:
    ssh_delay: "0" 
    ssh_timeout: "20"
    ssh_ping: true
  include_role:
    name: ssh
  when: ansible_distribution is not defined 
    or ansible_distribution is defined 
    and ansible_distribution == '' 

- name: Install packages
  become: yes
  package:
    name: "{{ packages }}"
    state: present
  vars:
    packages:
    - nfs-utils
    - multipath-tools 
    - unzip 
    - tftp-hpa
    - rsync

- name: Creates directory
  become: yes
  file:
    path: "{{item}}"
    state: directory
    # owner: nobody
    # group: nobody
    # mode: 0777
  with_items:
    - "/srv/nfs"
    - "/srv/tftp"
    - "{{pxe_img_dir}}"


- name: TFTP configuration
  become: yes
  run_once: true
  lineinfile:
    path: "/etc/conf.d/tftpd"
    line: 'TFTPD_ARGS="-s -4 /srv/tftp/"'
    regex: "TFTPD_ARGS="
    state: present

- name: Start service httpd, if not started
  service:
    name: "{{item}}"
    state: started
    enabled: true
  with_items:
    - tftpd
    - nfs-server

- name: Exports configuration
  become: yes
  lineinfile:
    path: "/etc/exports"
    line: "{{item}}"
    regex: "{{item}}"
    state: present
  register: _exports
  with_items:
    - "{{pxe_img_dir}} *(rw,sync,no_subtree_check,no_root_squash)"

- name: Reload exports
  become: yes
  command: exportfs -ra